### ISSUE TITLE
anatomy GTEx expression widget is not working properly

### ISSUE THREAD

**Issue by ctb** [nih-cfde/update-content-registry#20] opened 2022-07-01 16:40 UTC
see screenshot:

<img width="1138" alt="Screen Shot 2022-07-01 at 6 39 11 PM" src="https://user-images.githubusercontent.com/51016/176935849-eebe4df1-2dda-4909-b266-18674fdfdf45.png">

to my eyes, this does not _look_ like a problem with our markdown...

**Comment by ctb** [comment] 2022-07-01 16:41
@abradyIGS can you verify and bring in the appropriate person to look at this? thx :)

it works fine for genes, FWIW.

**Comment by abradyIGS** [comment] 2022-07-01 17:23
i was able to replicate, and confirm that for terms with known GTEx data available, it's still failing to parse the querystring parameter; query out to Jonathan, will relay reply

**Comment by abradyIGS** [comment] 2022-07-01 17:51
...wait a sec

i think this widget will only work if you use one of the terms available in the list that displays when you click the "add anatomical sites" button. there are not too many. (at least compared to the total set of UBERON terms.)

(`UBERON:0000167` isn't on that list. the widget does in fact work for IDs that are on the list, e.g. [this](https://mii.podvis.org/cfde-ge1/#/anatomy?uberon_ids=UBERON%3A0006631&width=1400&height=550&numTopGenes=25))

update: yep, jonathan crabtree confirmed my theory -- if you want him to update the error message to say something more explicit, go ahead and contact him, but by default i told him not to worry about it unless asked, because we can just limit our markdown generation (for this widget) to the allowed ID list.

**Comment by abradyIGS** [comment] 2022-07-01 17:51
closing; reopen if my answer wasn't satisfying

**Comment by raynamharris** [comment] 2022-07-19 17:31
very nice. thanks. I tried updating the list the exclude non-gtex uberons, but the blank oral cavity widget is still present for the oral cavity uberon. any ideas why? See #32 

note this is on staging :)

**Comment by raynamharris** [comment] 2022-08-03 20:52
I added some blank text to override the empty widgets in  https://github.com/nih-cfde/update-content-registry/pull/32/commits/47755495e3dfb90946fa91ff5df49bb7a62ed2d4# 

working on staging

**Closed as completed** 2022-08-18 22:40 UTC
Labels: anatomy
